#!/bin/bash

set -e

# For Kubernetes compatibility kill my_init since that is the process Docker is watching

if [ "$ORCH" = "kube" ]; then

	killall my_init

fi

/sbin/setuser node npm stop --prefix /opt/$PKG

sleep 10

touch /tmp/current-restarts

COUNT=`cat /tmp/current-restarts`
COUNT=$((COUNT+1))

echo "$COUNT" > /tmp/current-restarts

if [[ "$COUNT" -eq 3 ]]; then
sv down $PKG
rm /tmp/current-restarts

fi


